CREATE TABLE IF NOT EXISTS urls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS checks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    response_code INTEGER NOT NULL,
    header VARCHAR(255),
    title VARCHAR(255),
    description VARCHAR(255),
    url int,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY(url) REFERENCES urls(id) ON DELETE CASCADE ON UPDATE CASCADE
);
