<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page Analyzer</title>
</head>
<body>
    <div class="container">
        <?php if (!empty($flash)): ?>
            <p style="color: green"><?= $flash['success'][0]?></p>
        <?php endif; ?>

        <section>
            <h1>Site: <?= htmlspecialchars($url->getName()) ?></h1>
            <table>
                <tr>
                    <th scope="row">ID</th>
                    <td><?= $url->getId() ?></td>
                </tr>
                <tr>
                    <th scope="row">Имя</th>
                    <td><?= htmlspecialchars($url->getName()) ?></td>
                </tr>
                <tr>
                    <th scope="row">Дата создания</th>
                    <td><?= htmlspecialchars($url->getCreatedAt()) ?></td>
                </tr>
                </table>
        </section>
        
        <section>
           <h2>Checks:</h2>
           
           <form action="/checks" method="POST">
                <input type="hidden" name="url_id" value="<?= $url->getId() ?>">
                <button type="submit">Run a check</button>
            </form>

           <table>
               <thead>
                   <tr>
                       <th scope="col">ID</th>
                       <th scope="col">Код ответа</th>
                       <th scope="col">h1</th>
                       <th scope="col">title</th>
                       <th scope="col">description</th>
                       <th scope="col">Дата создания</th>
                   </tr>
               </thead>
               <tbody>
                    <?php foreach ($checks as $check): ?>
                   <tr>
                       <td><?= htmlspecialchars($check->getId()) ?></td>
                       <td><?= htmlspecialchars($check->getResponseName()) ?></td>
                       <td><?= htmlspecialchars($check->getHeader()) ?></td>
                       <td><?= htmlspecialchars($check->getTitle()) ?></td>
                       <td><?= htmlspecialchars($check->getDescription()) ?></td>
                       <td><?= htmlspecialchars($check->getCreatedAt()) ?></td>
                   </tr>
                   <?php endforeach; ?>
               </tbody>
           </table>
       </section>
        
        <p><a href="/">Back</a></p>
    </div>
</body>
</html>
