<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <div class="container">
        <h1>Login</h1>

        <?php if (!empty($flash)): ?>
            <p style="color: red"><?= $flash['error'][0]?></p>
        <?php endif; ?>

        <p>admin@project.io</p>
        
        <form action="/login" method="post">
            <input type="text" name="email" value="<?= htmlspecialchars($email) ?>">
            <input type="submit" value="Login">
        </form>
    </div>
</body>
</html>
