<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Url Analyzer</title>
</head>
<body>
    <div class="container">
        <h1>Url Analyzer</h1>
        <p>Проверяйте сайты на SEO пригодность https://vk.com</p>
                
        <form action="/urls" method="post">
            <div>
                <label for="url-name">
                    <input type="text" id="url-name" name="url[name]" value="<?= htmlspecialchars($url->getName() ?? '') ?>" required>
                </label>

                <?php if (isset($errors['name'])): ?>
                    <div><?= $errors['name'] ?></div>
                <?php endif ?>
            </div>

            <div>
                <button type="submit" title="Check url">Check</button>
            </div>
        </form>

        <p><a href="/urls">List</a></p>
    </div>
</body>
</html>
