<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность https://com-x.life/m</p>
                <form action="/urls" method="post" class="row">
                    <div class="col-8">
                        <label for="text" class="visually-hidden">Url для проверки</label>
                        <!-- url[name] откуда ? -->
                        <input 
                        type="text" 
                        name="url[name]" 
                        value="<?= htmlspecialchars($url['name'] ?? '') ?>" 
                        class="form-control form-control-lg <?= !empty($errors) ? 'is-invalid' : '' ?>"
                        placeholder="https://www.example.com"
                        required>
                        <?php if (!empty($errors)):
                            foreach ($errors as $error): ?>
                                <div class="invalid-feedback">
                                    <?= htmlspecialchars($error) ?>
                                </div>
                            <?php endforeach;
                        endif; ?>
                    </div>
                    <div class="col-2">
                        <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
