<?=$this->fetch('header.phtml', ["currentRoute" => 'home'])?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Url Analyzer</title>
</head>
<body>
<main class="flex-grow-1">
<div class="container-lg mt-3">
<h1 class="display-3">Анализатор страниц</h1>
<p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
        
        <form action="/urls" method="post" class="row">
            <div class="col-8">
            <label for="text" class="visually-hidden">Url для проверки</label>
                    <input type="text" name="url[name]" value="<?= htmlspecialchars($url['name'] ?? '') ?>" 
                    class="form-control form-control-lg <?= !empty($errors) ? 'is-invalid' : '' ?>"
                    placeholder="https://www.example.com"
                    required>
                
                    <?php if (!empty($errors)): ?>
                        <?php foreach ($errors as $error): ?>
                            <div class="invalid-feedback"><?= htmlspecialchars($error) ?></div>
                        <?php endforeach; ?>
                    <?php endif; ?>
            </div>

            <div class="col-2">
            <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
            </div>
        </form>

        <p><a href="/urls">List</a></p>
    </div>
    </main>
    <?=$this->fetch('footer.phtml')?>
</body>
</html>
