<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                <form action="/urls" method="post" class="row">
                    <div class="col-8">
                        <!-- 
                        * attribute name=“url[name]” organizes the data into an associative array with the name key and the value of the entered URL when submitting the form
                        * [
                        *    'url' => [
                        *        'name' => 'https://www.example.com'
                        *    ]
                        * ]
                        *
                        * content of the value attribute allows to save the entered URL so that the form displays the previously entered data (after submitting the form with errors) 
                        -->
                        <label for="text" class="visually-hidden">Url для проверки</label>
                        <input 
                        type="text" 
                        name="url[name]" 
                        value="<?= htmlspecialchars($url['name'] ?? '') ?>" 
                        class="form-control form-control-lg <?= !empty($errors) ? 'is-invalid' : '' ?>"
                        placeholder="https://www.example.com"
                        required>
                        <?php if (!empty($errors)):
                            foreach ($errors as $error): ?>
                                <div class="invalid-feedback">
                                    <?= htmlspecialchars($error) ?>
                                </div>
                            <?php endforeach;
                        endif; ?>
                    </div>
                    <div class="col-2">
                        <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
