 <?php if (!empty($flash['success'])): ?>
     <div class="alert alert-success"><?= htmlspecialchars($flash['success'][0]) ?></div>
 <?php endif; ?>
 <?php if (!empty($flash['info'])): ?>
     <div class="alert alert-success"><?= htmlspecialchars($flash['info'][0]) ?></div>
 <?php endif; ?>
 <?php if (!empty($flash['error'])): ?>
     <div class="alert alert-danger"><?= htmlspecialchars($flash['error'][0]) ?></div>
 <?php endif; ?>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Анализатор страниц</title>
</head>
<body>
    <main class="flex-grow-1">
     <div class="container-lg mt-3">

        <?php if (!empty($flash)): ?>
            <p style="color: green"><?= $flash['success'][0]?></p>
        <?php endif; ?>

            <h1>Site: <?= htmlspecialchars($url['name']) ?></h1>
            <div class="table-responsive">

            <table class="table table-bordered table-hover text-nowrap" data-test="url">
            <tbody>
                <tr>
                    <th scope="row">ID</th>
                    <td><?= htmlspecialchars($url['id']) ?></td>
                </tr>
                <tr>
                    <th scope="row">Имя</th>
                    <td><?= htmlspecialchars($url['name']) ?></td>
                </tr>
                <tr>
                    <th scope="row">Дата создания</th>
                    <td><?= htmlspecialchars($url['created_at']) ?></td>
                </tr>
        </tbody>
                </table>
            </div>
        

            <h2 class="mt-5 mb-3">Проверки</h2>

           <form action="/urls/<?= htmlspecialchars($url['id']) ?>/checks" method="POST" class="mb-3">

                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>

            <table class="table table-bordered table-hover" data-test="checks">
               <thead>
                   <tr>
                       <th scope="col">ID</th>
                       <th scope="col">Код ответа</th>
                       <th scope="col">h1</th>
                       <th scope="col">title</th>
                       <th scope="col">description</th>
                       <th scope="col">Дата создания</th>
                   </tr>
               </thead>
               <tbody>
                    <?php foreach ($checks as $check): ?>
                   <tr>
                   <td><?= htmlspecialchars($check['id']) ?></td>
                         <td><?= htmlspecialchars($check['status_code']) ?></td>
                         <td><?= htmlspecialchars($check['h1'] ?? '') ?></td>
                         <td><?= htmlspecialchars($check['title'] ?? '') ?></td>
                         <td><?= htmlspecialchars($check['description'] ?? '') ?></td>
                         <td><?= htmlspecialchars($check['created_at']) ?></td>
                   </tr>
                   <?php endforeach; ?>
               </tbody>
           </table>

        
        <p><a href="/">Back</a></p>
    </div>
    </main>
</body>
</html>
