<?=$this->fetch('header.phtml', ["currentRoute" => "urls"])?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Page Analyzer</title>
</head>
<body>
<main class="flex-grow-1">
<div class="container-lg mt-3"> 
        <h1>Sites</h1>
        <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="urls">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Последняя проверка</th>
                    <th scope="col">Код ответа</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($urls as $url): ?>
                <tr>
                    <td><?= htmlspecialchars($url['id']) ?></td>
                    <td><a href="/urls/<?= $url['id'] ?>"><?= htmlspecialchars($url['name']) ?></a></td>
                    <td><?= htmlspecialchars($url['data']['last_check']) ?></td>
                    <td><?= htmlspecialchars($url['data']['status_code']) ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        </div>

        <p><a href="/">Back</a></p>
    </div>
    </main>
 <?=$this->fetch('footer.phtml')?>
</body>
</html>
