<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Анализатор страниц</title>
</head>
<body>
<main class="flex-grow-1">
<div class="container-lg mt-3"> 
        <h1>Сайты</h1>
        <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="urls">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Последняя проверка</th>
                    <th scope="col">Код ответа</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($urls as $url): ?>
                <tr>
                    <td><?= htmlspecialchars($url['id']) ?></td>
                    <td><a href="/urls/<?= $url['id'] ?>"><?= htmlspecialchars($url['name']) ?></a></td>
                    <td><?= htmlspecialchars($url['latest_check'] ?? '') ?></td>
                    <td><?= htmlspecialchars($url['status_code'] ?? '') ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        </div>
    </div>
    </main>
</body>
</html>
