<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cars</title>
</head>
<body>
    <div class="container">
        <h1>Cars</h1>

        <?php if (isset($_SESSION['isAdmin'])): ?>
        <form action="/logout" method="post">
            <input type="hidden" name="_METHOD" value="DELETE">
            <input type="submit" value="Logout">
        </form>
        <?php endif; ?>

        <?php if (!empty($flash)): ?>
            <p style="color: green"><?= $flash['success'][0]?></p>
        <?php endif; ?>

        <p><a href="/cars/new">Add new car</a></p>

        <div>
            <form action="/cars" method="get">
                <label for="term">Find a mark:</label>
                <input type="search" name="term" id="term" value="<?= htmlspecialchars($term) ?>" />
                <button type="submit">Search</button>
            </form>
        </div>

        <hr>

        <?php if (empty($cars)): ?>
            <p>Nothing to display.</p>
        <?php endif; ?>

        <ul>
            <?php foreach ($cars as $car): ?>
            <li>
                <a href="/cars/<?= $car->getId() ?>">
                <?= $car->getId() ?>
                <?= htmlspecialchars($car->getMake()) ?>
                <?= htmlspecialchars($car->getModel()) ?>
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</body>
</html>
