<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
        <label>
            Имя *
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name'] ?? ''); ?>">
        </label>
        <?php if (isset($errors['name'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email *
            <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email'] ?? ''); ?>">
        </label>
        <?php if (isset($errors['email'])): ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Город *
            <select name="user[city]">
                <option value="">Выберите</option>
                <option <?= (isset($user['city']) && $user['city'] === '3') ? 'selected' : '' ?> value="3">Москва</option>
                <option <?= (isset($user['city']) && $user['city'] === '13') ? 'selected' : '' ?> value="13">Пенза</option>
                <option <?= (isset($user['city']) && $user['city'] === '399') ? 'selected' : '' ?> value="399">Томск</option>
            </select>
        </label>
        <?php if (isset($errors['city'])): ?>
            <div><?= $errors['city'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Обновить">
</form>
