<p style="color: green;">
  <?php if (!empty($flash['success'])): ?>
      <?= htmlspecialchars($flash['success'][0]) ?>
  <?php endif; ?>
</p>

<table>
  <?php 
  $cities = [
    '3' => 'Москва',
    '13' => 'Пенза',
    '399' => 'Томск'
  ];
  foreach ($users as $user): ?>
    <tr>
    <td>
        <?= htmlspecialchars($user['id']) ?>
    </td>
      <td>
          <?= htmlspecialchars($user['name']) ?>
      </td>
      <td>
          <?= htmlspecialchars($user['email']) ?>
      </td>
      <td>
          <?= htmlspecialchars($cities[$user['city']]) ?>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
